---
title: 异常处理
categories:
- JAVA
---

- [BASE](/JAVA/#BASE)
- [exception](/JAVA/#exception)
- [try.catch](/JAVA/#try.catch)
- [finally](/JAVA/#finally)
- [throws](/JAVA/#)

# BASE

java中的异常分为两类，error(错误)和exception(意外)

- error:系统级别的错误，比如操作系统引起的错误，这种错误一旦发生，JVM就不再继续运行了，JAVA程序无法捕获这种错误，因为即使捕获了，也没用，无法补救
- exception:这种错误是java可以捕获的，比如文件打不开，除以零等错误
    - RuntimeException:运行时的错误，比如除以零(发生这种意外一般是逻辑有问题)
    - checked Exception:比如文件打不开(逻辑没问题也可能发生这种意外)
--------------------

java将所有的不正常都放到`Throwable`类中,Exception类表示代表意外,系统内置里面更多的类都是Exception的子类

- Throwable类
    - Error
    - Exception类
        - 系统内置的exception(对应RuntimeException),分类很多
        - 非系统内置的(对应checked Exception),需要到对应的api中查看


# Exception

Exception这个类，有一些方法

-  `e.printStackTrace()`:打印栈的跟踪信息



# try.catch

```
try {
   fun();	
}catch(Exception e) {
    e.printStackTrace();
}
```
语法和js，PHP类似

# finally
语法和js，PHP类似
# throws

throws语法是java特有的

```
public void test(){}
```
如果这个方法exception了，那么会停下来的，不会继续执行

要么在test方法中写try语句，但是这个会破坏结构

java支持这种写法

```
public void test() throws Exception{}
```
这样如果有throws的话，它会往上传递错误，直到main入口

如果main入口不处理，也会报错

所以，throws只是往上传递异常，不会处理
